# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  evently.api:
    build:
      context: "/Users/user/Projects/Evently"
      dockerfile: "src/API/Evently.Api/Dockerfile"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Evently.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "eventlyapi:dev"
    ports: []
    volumes:
    - "/Users/user/Projects/Evently/src/API/Evently.Api:/app:rw"
    - "/Users/user/Projects/Evently:/src:rw"
    - "/Users/user/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
